# Generated by Django 5.0.3 on 2024-03-18 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisorSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_equity', models.FloatField(default=0.0)),
                ('average_equity', models.FloatField(default=0.0)),
                ('total_clients', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ClientSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('broker', models.CharField(choices=[('A', 'Corretora A'), ('B', 'Corretora B'), ('C', 'Corretora C')], default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.FloatField()),
                ('transaction_type', models.CharField(choices=[('Aporte', 'Aporte'), ('Resgate', 'Resgate')], max_length=7)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='datacontrol.clientsummary')),
            ],
        ),
    ]
